### ISSUE TITLE
Setup Obfuscation Tactic for EDRHunt constants.  Garble,  GoObfuscate fails to work properly.

### ISSUE THREAD

**Issue by achilles4828** [FourCoreLabs/edrRecon#3]
Tried using garble and gobfuscate to obfuscate string constants to prevent detections.

## garble

Compiles successfully with the `-literals` flag but EDRHunt fails to find correct system data somehow? As garble is obfuscating strings of all the dependencies it might happen that one of the libraries strings might be getting incorrectly obfuscated? Not sure.

**Comment by arush15june** [comment]
Fixed by using `go install mvdan.cc/garble@master` instead of `go install mvdan.cc/garble@latest`.
